### ISSUE TITLE
Invalid repository structure.

### ISSUE THREAD

**Issue by danmarsden** [jsxgraph/moodle-filter_jsxgraph#1]
Source code repositories for Moodle plugins should have the code sitting in the root folder of the repository (not inside a Moodle 2 or Moodle 2.9 folder.) and if you support multiple versions you need to do this with separate branches in your repository - eg a branch called "MOODLE_29" that supports 2.9 or "MOODLE_32" etc. - sometimes a "master" branch will support the "latest" versions.

You may want to take a look at other 3rd party Moodle plugins and how they structure their repositories to see how this works.

If you want to have your plugin listed in the official Moodle.org plugins database you will need to fix this prior to approval.

**Comment by walterandreas** [comment]
The different versions have been divided into different branches. Makefiles have been adjusted accordingly and now need to be executed in each branch separately. Also, each branch still contains a zip file in the install subfolder.

**Comment by danmarsden** [comment]
the zip shouldn't be there either. If people want a zip of the repo they will hit the green clone or download button in github here - which provides a "download as zip" link.

**Comment by walterandreas** [comment]
install/* and makefile have been removed, the documentation has been adjusted
