### ISSUE TITLE
missing thirdpartylib.xml file

### ISSUE THREAD

**Issue by danmarsden** [jsxgraph/moodle-filter_jsxgraph#11]
When you include a 3rd party lib in your plugin you need to add a file to describe the details - please see here for more details on this:
https://docs.moodle.org/dev/Third_Party_Libraries

**Comment by walterandreas** [comment]
I have created the appropriate files (thirdpartylib.xml and readme_moodle.txt). In my test environment, the library is listed under 3rd party libraries. Please re-open the issue if I have forgotten something.
