### ISSUE TITLE
JSXGraph only create one jsxgraph in a 'quiz'.

### ISSUE THREAD

**Issue by pbelle** [jsxgraph/moodle-filter_jsxgraph#12]
Hi, I´m trying to build a 'quiz' in moodle and only one jsxgraph apear correctly. If I try to create more then one jsxgraph, this newone apear in blank!
The idea was to put one jsxgraph per alternative in a multiple choice quiz!

Is there any solution to this problem? 

Thank you,

<img width="683" alt="2019-05-23" src="https://user-images.githubusercontent.com/16501768/58223302-7ac0e280-7cef-11e9-88b4-d6551356a55e.png">

**Comment by walterandreas** [comment]
Hello. 
Thank you for your interest in our Moodle filter. Could you please post the code of the two used JSX-applications including the <jsxgraph> tags here. We will try to find a solution to your problem.
Greetings, Andreas

**Comment by pbelle** [comment]
Hello Andreas, sorry about my delay, and thank you for your support. 
I´m not a especialist in html programming, so may be I´m making an elementary mistake. 
I just copied one example from the examples pages and paste it in the choices. I only changed the object name.
The codes I wrote there are the following:

Alternative a)
<jsxgraph height="300" width="300">
    (function() {
        var brd2 = JXG.JSXGraph.initBoard('box1', {boundingbox:[-5,5,5,-5], axis:true});
        var p2 = brd2.create('point', [1,2]);
    })();
</jsxgraph>

Alternative b)
<jsxgraph height="200" width="300">
    (function() {
        var brd = JXG.JSXGraph.initBoard('box0', {boundingbox:[-5,5,5,-5], axis:true});
        var p = brd.create('point', [2,2]);
    })();
</jsxgraph>

The idea was obviously to make 2 graphs for the student select the proper one.

Best regards,
Paulo Belletato.

**Comment by walterandreas** [comment]
Dear Paulo,

I am very sorry that I am only now reporting, but my exams dominate my schedule.

Thanks for your code posts. Could you please try to add the attribute box="" to the two <jsxgraph-tags. At alternative a) you would have to write <code>box="box1"</code>, at b) <code>box="box0"</code>. How is it then?

A second solution could also be to swap the two boxes. Maybe the board at alternative a) has to be named to "box0" and alternative b) to "box1". That means you would have to change the code to:

<code>
(function() {
var brd2 = JXG.JSXGraph.initBoard('box0', {boundingbox:[-5,5,5,-5], axis:true});
var p2 = brd2.create('point', [1,2]);
})();
</code>

and

<code>
(function() {
var brd = JXG.JSXGraph.initBoard('box1', {boundingbox:[-5,5,5,-5], axis:true});
var p = brd.create('point', [2,2]);
})();
</code>


Please test these two solutions and then get in touch again! I hope I could help you.

Andreas

**Comment by pbelle** [comment]
Dear Andreas,
I´ve tried both of your sugestions but unfortunatly, didn´t worked!
I have already tried using the second sugestion, using both single quotes, as well as, double quotes.
Unfortunatly, didn´t worked also.

Can we try any other solution?
Best regards,
Paulo

**Comment by walterandreas** [comment]
Dear Paulo,

that is very strange. I tried the first suggestion from my [post on 2 August](#issuecomment-517701664) in a test environment. Everything works perfect for me:
![moodle1](https://user-images.githubusercontent.com/30598361/66400151-3bb2d580-e9e1-11e9-855f-23948b30739d.png)

I have used the following settings:
![moodle2](https://user-images.githubusercontent.com/30598361/66400169-42d9e380-e9e1-11e9-9393-de7422a1a6df.png)

Could it be that another plugin or filter is blocking the functionality of JSX? I use the default global JSX filter settings.

Best regards
Andreas

**Comment by pbelle** [comment]
Dear Andreas,

I will try to verify my installation of Moodle and the plugins installed.
But I´m very grateful for your assistance, and also excited to see that it
worked in your system.

Thank you Andreas,

Best regards,
Paulo Belletato.


Em ter, 8 de out de 2019 às 10:37, A. Walter <notifications@github.com>
escreveu:

**Comment by alfredwassermann** [comment]
Dear Paulo,
can you please tell us, if there are any error messages in the JavaScript console?
Best wishes,
Alfred

**Comment by walterandreas** [comment]
Please note our new functionality that the boardID is saved in a variable and try to use it. Maybe that will fix your problem.

**Comment by andreas-web** [comment]
Because Paulo stopped answering, I mark this issue as closed. If there are still problems you can reopen it.
