### ISSUE TITLE
Moodle convert && to &amp;&amp; inside javascript IF statements, and breaks JSXgraph

### ISSUE THREAD

**Issue by nadavkav** [jsxgraph/moodle-filter_jsxgraph#17]
Moodle convert the javascript code that includes the logical AND characters && to &amp;&amp; inside javascript IF statements, and breaks the JSXgraph filter code.

Can you wrap the JS code and add / / < ! [ CDATA [    jsxcode    / / ] ] > 
to workaround it?

**Comment by andreas-web** [comment]
commit cea6c445f1c27275d163c12f7f479c72bb519ccb
