### ISSUE TITLE
After upgrade to Version 1.1.0-improved settings cannot be saved anymore.

### ISSUE THREAD

**Issue by mputzi** [jsxgraph/moodle-filter_jsxgraph#18]
After upgrade to Version 1.1.0-improved settings of **any** plugin cannot be saved anymore.
There seems to be a critical problem with putting the declaration of the get_version method in settings.php.
Every time I try to save the settings of **any** plugin in the moodle system I get the following error:
`Fatal error: Cannot redeclare get_jsxfilter_version() (previously declared in /var/www/vhosts/.../httpdocs/moodle/filter/jsxgraph/settings.php:56) in /var/www/vhosts/.../httpdocs/moodle/filter/jsxgraph/settings.php on line 55`
The workaround at the moment is removing the jsxgraph plugin and reinstalling an older version.

**Comment by walterandreas** [comment]
Hello! Thanks for your message. We know about this problem yet. I think it will be solved tomorrow.

**Comment by walterandreas** [comment]
Solved by v1.1.0-improved2
