### ISSUE TITLE
1.6 - displays whole numbers to two decimal places.

### ISSUE THREAD

**Issue by easyflhomeschool** [jsxgraph/moodle-filter_jsxgraph#39]
I prefer my young students see whole numbers on the screen.   All the numbers changed to decimal numbers to 2 places.   The text on the screen is now showing quotes around it.    I went back to version 1.5 and have no issues.   
![jsxversions](https://github.com/jsxgraph/moodle-filter_jsxgraph/assets/73344910/f0fafe43-2ebc-48bf-80d9-f50c835981d3)

**Comment by alfredwassermann** [comment]
Sorry about that. A fix should be to add 

    JXG.Options.text.digits = 0;

__before__ calling `initBoard`. What about the quotation marks around `-` in the right image? Can you please post a snippet how you construct these numbers and texts?

Best wishes,
Alfred

**Comment by easyflhomeschool** [comment]
Will the fix be added and released for install?
do I need to add the line to every question to force zero digits?
Thank you,
Wendy

**Comment by alfredwassermann** [comment]
Sorry about the inconvenience. This regression will be fixed in the upcoming new release.
