### ISSUE TITLE
Code precheck failures

### ISSUE THREAD

**Issue by danmarsden** [jsxgraph/moodle-filter_jsxgraph#4]
moodle.org plugins db runs a number of coding guideline checks on your code - not all of these failures are blockers for approval in the plugins db but you will need to fix the issues it reports about file headers/missing licences and Moodle_internal checks that are missing.

To see the full list of code precheck failures go here:
https://moodle.org/plugins/pluginversions.php?id=2115&validation=1

and click on the "code prechecks" button beside the version of your code that supports 2.9 and higher.

**Comment by walterandreas** [comment]
Some code prechecks have been removed using travis. Some errors and warnings (e.g. coding style: naming variables and functions) were ignored for the sake of better legibility. Moodle_internal checks and licenses have been added.
