### ISSUE TITLE
thirdpartylibs.xml refers to a non-existent file. Breaks grunt *everywhere*

### ISSUE THREAD

**Issue by thepurpleblob** [jsxgraph/moodle-filter_jsxgraph#40]
thirdpartylibs.xml has a reference to file amd/build/jsxgraphcore-v0.82-lazy.js which does not exist.

This causes 'grunt' to fail anywhere it is run in Moodle with an error for the missing file. 

Verson, 2023081700

**Comment by andreas-web** [comment]
fixed by #b651d02e63c49872b47478c6a1a0ba3b8421c9cc
