### ISSUE TITLE
Text renders with double quotes around it

### ISSUE THREAD

**Issue by idleup** [jsxgraph/moodle-filter_jsxgraph#41]
Board.create('text', [1, -1 'MyText']) 

Will render with the word "MyText" on the chart with double quotes around it. Is that a setting? a bug? The samples on JSXGraph do not do this, only when Graphs are created in Moodle (specifically in questions)

**Comment by alfredwassermann** [comment]
A quick work around is to use the attribute `parse:false` :

```
board.create('text', [1, -1, 'MyText'], {parse:false});
```

It is still not clear how moodle interferes with JSXGraph.

**Comment by alfredwassermann** [comment]
Finally, the root of the problem with quotation marks could be identified:
Moodle seems to manipulate the method String.at() and does not support negative values for the parameter (as does the original method).
This is fixed now, a new version will be published soon.
