### ISSUE TITLE
Moodle 4.4

### ISSUE THREAD

**Issue by easyflhomeschool** [jsxgraph/moodle-filter_jsxgraph#43]
I am testing Moodle 4.4 on my website.   Unfortunately when I add a JSX graph tag, it disappears and will not display JSX graph on the screen.    is this a bug, or intentional of Moodle 4.4?

**Comment by Ferenc-Frank-Lengyel** [comment]
In Moodle 4.4 the default text editor is the new TinyMCE instead of the ATTO editor. Unfortunately, Tiny removes the `<jsxgraph>` tags and replaces them with `<p>`. Try to use the old Atto (which will be discontinued soon) or use the plain text area instead. Both worked for me.

**Comment by andreas-web** [comment]
Thank you @Ferenc-Frank-Lengyel for your answer. You are right. Unfortunately we can't do anything for that on our side.

Therefore I will close this issue. @easyflhomeschool feel free to reopen it, if you are of the opinion that we can do something.
