### ISSUE TITLE
plugins settings should not use global scope

### ISSUE THREAD

**Issue by danmarsden** [jsxgraph/moodle-filter_jsxgraph#7]
Plugins should not pollute the core $CFG vars and should use the config plugins table instead.

to do this you replace this sort of code:
new admin_setting_configcheckbox('filter_jsxgraph_jsxfromserver',
with this:
new admin_setting_configcheckbox('filter_jsxgraph/jsxfromserver',

and then use the core function "get_config()" to obtain the data.

Please note - this is not a blocker for approval in the plugins database (some of the older core Moodle filters still use the global $CFG var instead of the proper location too.)

**Comment by walterandreas** [comment]
done
